In [2]:
import numpy as np
import pandas as pd

In [3]:
stations_df = pd.read_csv('stations.csv', ';')
clusters_df = pd.read_csv('district_stops.csv', ';')
districts_df = pd.read_csv('district_groups.csv', ';')
stations_df

,ID_STOP,STOP_NAME,ID_TRANSPORT,STOP_NAME_SHORT,LATITUDE,LONGITUDE
0,2246,УЛ. КОРАБЛЕСТРОИТЕЛЕЙ,1,"УЛ. КОРАБЛЕСТРОИТЕЛЕЙ [1, 6]","59,954712","30,235202"
1,2424,"УНИВЕРСАМ ""ГАВАНСКИЙ""",1,"УНИВЕРСАМ ""ГАВАНСКИЙ"" [6]","59,950731","30,232945"
2,2096,"СТ. МЕТРО ""ПРИМОРСКАЯ""",1,"СТ. МЕТРО ""ПРИМОРСКАЯ""","59,948813","30,23169"
3,20878,НОВОСМОЛЕНСКАЯ НАБ.,1,НОВОСМОЛЕНСКАЯ НАБ.,"59,946792","30,230576"
4,2278,УЛ. НАХИМОВА,1,"УЛ. НАХИМОВА [1, 6]","59,942173","30,231239"
5,1672,"МАЛЫЙ ПР. В.О.,УГ. НАЛИЧНОЙ УЛ.",1,"МАЛЫЙ ПР. В.О.,УГ. НАЛИЧНОЙ УЛ. [6, 1]","59,937534","30,23602"
6,4489,ШКИПЕРСКИЙ ПРОТОК,1,ШКИПЕРСКИЙ ПРОТОК,"59,93459","30,23859"
7,2054,СРЕДНИЙ ПР. В.О.,1,"СРЕДНИЙ ПР. В.О. [1, 24]","59,932126","30,239846"
8,4490,БОЛЬШОЙ ПР. В.О.,1,БОЛЬШОЙ ПР. В.О.,"59,927678","30,2421"
9,1434,ВЕСЕЛЬНАЯ УЛ.,1,ВЕСЕЛЬНАЯ УЛ. [7],"59,928251","30,246212"
10,24986,NaN,1,ДЕТСКАЯ УЛ.,"59,929125","30,249777"
11,2514,28-29 ЛИНИИ (ПО СРЕДНЕМУ ПР. В.О.),1,28-29 ЛИНИИ (ПО СРЕДНЕМУ ПР. В.О.),"59,934789","30,250447"
12,27114,NaN,1,"22-23-Я ЛИНИИ В.О., УГ. СРЕДНЕГО ПР. В.О.","59,936607","30,258782"
13,27115,NaN,1,"БОЛЬШОЙ ПР. В.О., УГ. 22-23-Й ЛИНИИ В.О.","59,933904","30,261839"
14,1286,16 И 17 ЛИНИИ,1,"16 И 17 ЛИНИИ [7, 1]","59,935551","30,271146"
15,1329,8 И 9 ЛИНИЯ ПО БОЛЬШОМУ ПР.,1,8 И 9 ЛИНИЯ ПО БОЛЬШОМУ ПР. [1],"59,939111","30,280002"
16,3248,"СТ. МЕТРО ""ВАСИЛЕОСТРОВСКАЯ""",1,"СТ. МЕТРО ""ВАСИЛЕОСТРОВСКАЯ""","59,94349","30,28021"
17,1569,КАДЕТСКАЯ ЛИНИЯ УГ. СРЕДНЕГО ПР.,1,КАДЕТСКАЯ ЛИНИЯ УГ. СРЕДНЕГО ПР. [1],"59,94587","30,28571"
18,2254,УЛ. КРАСНОГО КУРСАНТА,1,УЛ. КРАСНОГО КУРСАНТА [1],"59,953625","30,289698"
19,1775,ПИОНЕРСКАЯ УЛ.,1,ПИОНЕРСКАЯ УЛ. [1],"59,957421","30,29106"
20,2106,"СТ. МЕТРО ""ЧКАЛОВСКАЯ""",1,"СТ. МЕТРО ""ЧКАЛОВСКАЯ""","59,960956","30,291218"
21,2264,УЛ. ЛЕНИНА УГ. ЧКАЛОВСКОГО ПР.,1,УЛ. ЛЕНИНА УГ. ЧКАЛОВСКОГО ПР. [1],"59,964495","30,298121"
22,1391,БОЛЬШОЙ ПР. П.С.,1,БОЛЬШОЙ ПР. П.С.,"59,961902","30,304872"
23,18086,УЛ. ЛЕНИНА,1,УЛ. ЛЕНИНА [128],"59,961429","30,30805"
24,4491,ОРДИНАРНАЯ УЛ.,1,ОРДИНАРНАЯ УЛ.,"59,964125","30,312269"
25,2087,"СТ. МЕТРО ""ПЕТРОГРАДСКАЯ""",1,"СТ. МЕТРО ""ПЕТРОГРАДСКАЯ"" [1, 46А]","59,966561","30,310934"
26,2312,УЛ. ПРОФЕССОРА ПОПОВА,1,"УЛ. ПРОФЕССОРА ПОПОВА [1, 46А]","59,971611","30,306376"
27,2162,УЛ. АКАДЕМИКА ПАВЛОВА,1,"УЛ. АКАДЕМИКА ПАВЛОВА [1, 46А]","59,975917","30,303054"
28,2781,КАМЕННЫЙ ОСТРОВ,1,КАМЕННЫЙ ОСТРОВ [46А]<,"59,979401","30,299787"
29,4056,"СТ.МЕТРО ""ЧЁРНАЯ РЕЧКА""",1,"СТ.МЕТРО ""ЧЁРНАЯ РЕЧКА""","59,987171","30,302567"
...,...,...,...,...,...,...
7640,29374,КТ,1,NaN,"59,88184719","30,4699211"
7641,29375,КТ,1,NaN,"59,87051122","30,4775467"
7642,29376,КТ,1,NaN,"59,97499339","30,4155903"
7643,29377,КТ,1,NaN,"59,74061126","30,5973892"
7644,29378,КТ,1,NaN,"59,73536893","30,6112442"
7645,29379,КТ,1,NaN,"59,74741852","30,6103916"
7646,29380,КТ,1,NaN,"60,12244087","29,9767075"
7647,29381,КТ,1,NaN,"60,16575271","29,8620148"
7648,29382,КТ,1,NaN,"60,08996552","29,9646511"
7649,29383,КТ,1,NaN,"60,01155258","29,7251339"
7650,29384,КТ,1,NaN,"59,72449957","30,0800381"
7651,29385,КТ,1,NaN,"59,75413495","30,1056976"
7652,29386,КТ,1,NaN,"59,78090809","30,1342049"
7653,29404,КТ,1,NaN,"59,7183627","30,2822723"
7654,29405,КТ,1,NaN,"59,70365648","30,3719177"
7655,29406,КТ,1,NaN,"59,7445244","30,3097916"
7656,29407,КТ,1,NaN,"60,31625623","30,2654762"
7657,29408,КТ,1,NaN,"59,90782271","30,9870319"
7658,29409,КТ,1,NaN,"59,89200753","30,5238628"
7659,29410,КТ,1,NaN,"59,89677651","30,6776848"
7660,29411,КТ,1,NaN,"59,91088074","30,9311275"
7661,29416,КТ,1,NaN,"59,6648533","30,5317307"
7662,29417,КТ,1,NaN,"59,69548242","30,437561"
7663,29418,КТ,1,NaN,"59,96178485","30,4685345"
7664,29419,КТ,1,NaN,"60,0092686","30,6139908"
7665,29420,КТ,1,NaN,"60,082213","30,3583565"
7666,29421,КТ,1,NaN,"60,04045228","30,4384575"
7667,29485,"УЛ. БОРИСОВА, Д.7",1,NaN,"60,10204709","29,9712009"
7668,29486,РЕАБИЛИТАЦИОННЫЙ ЦЕНТР,1,NaN,"60,10358251","29,9654465"
7669,29487,УЛ. ПОГРАНИЧНИКОВ,1,NaN,"60,10645229","29,9674206"

In [112]:
stations_df[stations_df['ID_STOP'] == 1780]

,ID_STOP,STOP_NAME,ID_TRANSPORT,STOP_NAME_SHORT,LATITUDE,LONGITUDE
257,1780,"ПИСКАРЁВСКИЙ ПР., 50",1,"ПИСКАРЁВСКИЙ ПР., 50","59,99004","30,4313"

In [108]:
clusters_df[clusters_df['ID_STOP'] == 1664]

,ID_STOP,ID_STOP_GROUP,ID_TRANSPORT_DISTRICT,ID_DISTRICT_PART,ID_DISTRICT,ID_PLAN_ZONE
816,1664,875,617,1028.0,114.0,2002.0

In [110]:
clusters_df[clusters_df['ID_STOP_GROUP'] == 1491]

,ID_STOP,ID_STOP_GROUP,ID_TRANSPORT_DISTRICT,ID_DISTRICT_PART,ID_DISTRICT,ID_PLAN_ZONE
916,1780,1491,553,1029.0,114.0,2002.0
4668,16860,1491,553,1029.0,114.0,2002.0

In [ ]:
stops_191 = '21667,3463,26825,1351,1531,2186,2223,1788,4376,3069,1664,1535,4215,2744,2730,4314,3374,3504,3086,3414,1892,17839,2058,2677,2010,1462,2377,7069,3615,3096,4589,2285,22481,20777'
clusters_191 = ""
for stop in stops_191.split(','):